version: "3"

services:
  smartmetserver-backend:
    image: fmidev/smartmetserver-backend
    ports:
     - "8080:8080"
    volumes:
      - $HOME/docker-smartmetserver/smartmet/data:/smartmet/data
      - $HOME/docker-smartmetserver/smartmet/share:/smartmet/share
      - $HOME/docker-smartmetserver/smartmetconf:/etc/smartmet/conf
    networks:
      smartmet-server-network:
        ipv4_address: 10.5.0.5

networks:
  smartmet-server-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
