version: "3"

services:
  smartmetserver-frontend:
    image: fmidev/smartmetserver-frontend
    ports:
     - "8080:8080"
    volumes:
      - $HOME/smartmet/data:/smartmet/data
      - $HOME/smartmet/share:/smartmet/share
      - $HOME/brainstorm/cache/frontend-compressed-cache:/brainstorm/cache/frontend-compressed-cache
      - $HOME/repos/docker-smartmetserver/smartmetconf:/etc/smartmet/conf
    networks:
      smartmet-server-network:
        ipv4_address: 10.5.0.6

networks:
  smartmet-server-network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
